apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-hub-site-deployment
spec:
  selector:
    matchLabels:
      app: event-hub-site
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: event-hub-site
        tier: frontend
        track: stable
    spec:
      containers:
      - name: event-hub-site
        image: "gcr.io/event-hub-249001/event-hub-site:0.0.1-SNAPSHOT"
        imagePullPolicy: "Always"
      env:
      - name: spring.profiles.active
        value: gcp
