# Default values for event-hub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: gcr.io
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: "event-hub-site"
fullnameOverride: "event-hub-site-chart"
gcp_project: "event-hub-317019"

